<a href="https://colab.research.google.com/github/Soumyoj/ML-AI-Python/blob/main/Soumyojyoti_Sen_Python_for_Data_Science_and_AI_Certification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x =2
x = x+2
x

4

In [ ]:
int(False)

0

In [ ]:
'1'+'2'

'12'

In [ ]:
 str(1)+str(1)

'11'

In [ ]:
"ABC".replace("AB", "ab")

'abC'

In [ ]:
"123".replace("12", "ab")

'ab3'

In [ ]:
 x=2/2
 x

1.0

In [ ]:
 A=((1),[2,3],[4])
 A[2]

[4]

In [ ]:
 A=((11,12),[21,22])
 A[0][1]

12

In [ ]:
A=["hard rock",10,1.2]
del(A[0])

In [ ]:
A

[10, 1.2]

In [ ]:
B=A[:]
B

[10, 1.2]

In [ ]:
len(("disco",10))

2

In [ ]:
{"The Bodyguard":"1992", "Saturday Night Fever":"1977"}

{'Saturday Night Fever': '1977', 'The Bodyguard': '1992'}

In [ ]:
V={'A','B'}
V.add('C')
V

{'A', 'B', 'C'}

In [ ]:
'A' in {'A','B'}

True

In [ ]:
x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')

Go 
Mike


In [ ]:
x=1
x>-5

True

In [ ]:
x=5
while(x!=2):
  print(x)
  x=x-1

5
4
3


In [ ]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points("A","B")
p1.print_point()

x= A  y= B


In [ ]:
for i,x in enumerate(['A','B','C']):
    print(i,2*x)

0 AA
1 BB
2 CC


In [ ]:
class Points(object):

  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x='A'

p2.print_point()

x= A  y= 2


In [ ]:
a=1

def do(x):
    a=100
    return(x+a)

print(do(1))

101


In [ ]:
import numpy as np
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b)

0

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [ ]:
X=np.array([[1,0,1],[2,2,2]])
out=X[0,1:3]
out

array([0, 1])

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [ ]:
with open('/content/Example1.txt',"r") as file1:

    FileContent=file1.read()

    print(FileContent)

This is line 1

This is line 2

This is line 3


In [ ]:
with open('/content/Example1.txt',"w") as writefile:

  writefile.write("This is line A\n")
  writefile.write("This is line B\n")

In [ ]:
with open('Example1.txt','r') as readfile:
    with open('Example3.txt','w') as writefile:
          for line in readfile:
                writefile.write(line)


In [ ]:
var = '01234567'
print(var[::2])

0246


In [ ]:
Name="ABCDE"
Name.find("B")

1

In [ ]:
int(3.99)

3

In [ ]:
1//2

0

In [ ]:
1/2

0.5

In [ ]:
2//3


0

In [ ]:
'1:2,3:4'.split(':')

['1', '2,3', '4']

In [ ]:
def add(x):
  return(x+x)
add('1')

'11'

In [ ]:
A=[8,5,2]
for a in A:
  print(12-a)

4
7
10


In [ ]:
for i in range(1,5):
  if (i!=1):
    print(i)

2
3
4


In [ ]:
for i in range(1,5):
  if (i!=2):
    print(i)

1
3
4


In [ ]:
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a+b

array([1, 1, 1, 1, 1])

In [ ]:
a=np.array([1,1,1,1,1])
a+10

array([11, 11, 11, 11, 11])

In [ ]:
type(int(12.3))

int

In [ ]:
int(False)

0

In [ ]:
'1'+'2'

'12'

In [ ]:
'hello'.upper()

'HELLO'

In [ ]:
str(1+1)

'2'

In [ ]:
"ABC".replace("AB", "ab")

'abC'

In [ ]:
x=1/1
x

1.0

In [ ]:
A=((1),[2,3],[4])
A[2]

[4]

In [ ]:
A=((11,12),[21,22])
A[0][1]

12

In [ ]:
A=["hard rock",10,1.2]
del(A[0])
A

[10, 1.2]

In [ ]:
x = 3

In [ ]:
len(("disco",10))

2

In [ ]:
V={'1','2'}
V.add('3')
V

{'1', '2', '3'}

In [ ]:
'A' in {'A','B'}

True

In [ ]:
x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')

Go 
Mike


In [ ]:
x=1
x>-5

True

In [ ]:
x=0
while(x<2):
    print(x)
    x=x+1

0
1


In [ ]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p1=Points(1,2)
p1.print_point()

x= 1  y= 2


In [ ]:
for i,x in enumerate(['A','B','C']):
    print(i+1,x)

In [ ]:
class Points(object):
  def __init__(self,x,y):

    self.x=x
    self.y=y

  def print_point(self):

    print('x=',self.x,' y=',self.y)

p2=Points(1,2)

p2.x=2

p2.print_point()

x= 2  y= 2


In [ ]:
def step(x):
    if x>0:
        y=1
    else:
        y=0
    return y
step(1)

1

In [ ]:
a=1

def do(x):
    return(x+a)

print(do(1))

2


In [ ]:
import numpy as np
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b)

0

In [ ]:
X=np.array([[1,0,1],[2,2,2]])
out=X[0,1:3]
out

array([0, 1])

In [ ]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]])
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [ ]:
var = '01234567'
print(var[::2])

0246


In [ ]:
Name="ABCDE"
Name.find("B")

1

In [ ]:
float(3)

3.0

In [ ]:
1/2

0.5

In [ ]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [ ]:
'1,2,3,4'.reverse(',')

AttributeError: ignored

In [ ]:
def add(x):
  return(x+x)
add(1)

2

In [ ]:
A=[8,5,2]
for a in A:
  print(12-a)

4
7
10


In [ ]:
for i in range(1,5):
   if (i==2):
     print(i)

2


In [ ]:
for i in range(1,5):
  if (i!=1):
    print(i)

2
3
4


In [ ]:
for i in range(1,5):
  if (i!=2):
    print(i)

1
3
4


In [ ]:
 a=np.array([0,1,0,1,0])
 b=np.array([1,0,1,0,1])
 a/b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0., inf,  0., inf,  0.])

In [ ]:
a=np.array([1,1,1,1,1])
a+1

array([2, 2, 2, 2, 2])